apiVersion: v1
kind: Service
metadata:
  name: bench-service
  labels:
    app: bench
  namespace: beta
spec:
  ports:
  - port: 80
    name: bench-service-port-80
  clusterIP: None
  selector:
    app: bench
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bench-statefulset
  namespace: beta
spec:
  selector:
    matchLabels:
      app: bench # 必须匹配 .spec.template.metadata.labels
  serviceName: "bench"
  replicas: 1 # 默认值是 1
  minReadySeconds: 10 # 默认值是 0
  template:
    metadata:
      labels:
        app: bench # 必须匹配 .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bench
        image: 1447333108/bench:latest
        ports:
        - containerPort: 80
          name: bench
        volumeMounts:
        - name: bench-pvc
          mountPath: /data/
  volumeClaimTemplates:
  - metadata:
      name: bench-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp3"
      resources:
        requests:
          storage: 10Gi